// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFDmWSbxKunL-hL70ySLqKqqtJ6HHmF7o',
    appId: '1:935380100149:web:69b812a95feceab0443d7c',
    messagingSenderId: '935380100149',
    projectId: 'fir-50115',
    authDomain: 'fir-50115.firebaseapp.com',
    storageBucket: 'fir-50115.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD1w-OI3HcaKr3rxaJVS8T7vDjAKrjIEE',
    appId: '1:935380100149:android:1c6f76bc94f2515b443d7c',
    messagingSenderId: '935380100149',
    projectId: 'fir-50115',
    storageBucket: 'fir-50115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQOQjy6PyIsB-ILxpXVDMznsCPrZ-0XR4',
    appId: '1:935380100149:ios:7a5013e0a0fc52e0443d7c',
    messagingSenderId: '935380100149',
    projectId: 'fir-50115',
    storageBucket: 'fir-50115.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQOQjy6PyIsB-ILxpXVDMznsCPrZ-0XR4',
    appId: '1:935380100149:ios:7a5013e0a0fc52e0443d7c',
    messagingSenderId: '935380100149',
    projectId: 'fir-50115',
    storageBucket: 'fir-50115.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFDmWSbxKunL-hL70ySLqKqqtJ6HHmF7o',
    appId: '1:935380100149:web:ed2213c42d4b80b8443d7c',
    messagingSenderId: '935380100149',
    projectId: 'fir-50115',
    authDomain: 'fir-50115.firebaseapp.com',
    storageBucket: 'fir-50115.firebasestorage.app',
  );
}
